name: Rust-Evn

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  ANIL_ENV: anil

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANIL_ENV_JOB: job
    steps:
    - name: test-build2
      env:
        ANIL_ENV_STEP: steps
      run: |
        echo  ${{ env.ANIL_ENV }}
        echo  $ANIL_ENV_JOB
        echo  $ANIL_ENV_STEP
      shell: bash
    - name: evn
      run: |
         echo "test=world" >> "$GITHUB_OUTPUT"
         echo  ${{ env.ANIL_ENV }}
         echo  $ANIL_ENV_JOB
         echo  $ANIL_ENV_STEP
      shell: bash
  build2:
      runs-on: ubuntu-latest
      needs:  build
      steps:
      - name: test-build2
        run: |
          echo  ${{ env.ANIL_ENV }}
          echo  $ANIL_ENV_JOB
          echo  $ANIL_ENV_STEP
        shell: bash
      - name: evn
        run: |
          echo "test=world" >> "$GITHUB_OUTPUT"
          echo  ${{ env.ANIL_ENV }}
          echo  ${{ needs.build.env.ANIL_ENV_JOB }}
          echo  ${{ needs.build.env.ANIL_ENV_STEP }}
        shell: bash