name: Rust-Evn

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build1:
    runs-on: self-hosted
    steps:
    - name: step1
      run: echo $INPUT_P1   $INPUT_P2
      shell: powershell

    - name: step2
      run: echo $INPUT_P1   $INPUT_P2
      shell: powershell

  build2:
      runs-on: self-hosted
      needs:  build1
      steps:
      - name: step1
        run: |
          echo "Anil Test"
        shell: powershell
