name: Rust-Evn

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo $INPUT_P1   $INPUT_P2
      shell: bash

    - name: step2
      run: |
        echo  ${{ jobs.build1.steps[0].name }}
        echo ${{ jobs.build1.steps[1].name }}
      shell: bash

  build2:
      runs-on: ubuntu-latest
      needs:  build1
      steps:
      - name: step1
        run: |
          echo ${{ needs.build1[0].name }}  ${{ jobs.build1[0].name }}
          echo ${{ needs.build1[1].name }}  ${{ jobs.build1[1].name }}
        shell: bash