name: Anil-test-pipline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:
    inputs:
      workflow_username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
env:
  ANIL_ENV: anil
  myExponentialNumber: ${{ -2.99e-2 }}
  
jobs:
  build1:
    runs-on: self-hosted
    if: github.repository == 'anilWu/file-scan'
    outputs:
      output1: ${{ steps.step2.outputs.test }}
    steps:
    - name: step1
      run:  |
          echo  3+3  >> math-homework.txt
      shell: powershell
      env:
          step1_env: 5432
      if: ${{ env.step1_env == 5432 }} 

    - id: step2
      run: echo "test=world" >> %GITHUB_OUTPUT%
      shell: powershell
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
          name: homework
          path: math-homework.txt
    - name: step3
      run: sleep 1

  build2:
      runs-on: self-hosted
      needs:  build1
      steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1" 
        shell: powershell
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: homework
