name: Rust-Evn

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:
    inputs:
      workflow_username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
env:
  CARGO_TERM_COLOR: always
  ANIL_ENV: anil
  myExponentialNumber: ${{ -2.99e-2 }}
  
jobs:
  build1:
    runs-on: self-hosted
    if: github.repository == 'anilWu/file-scan'
    outputs:
      output1: echo The username is ${{ inputs.workflow_username }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - name: step1
      run:  |
          echo  3+3  >> math-homework.txt
      shell: powershell
      env:
          step1_env: 5432
      if: ${{ env.step1_env == 5432 }} 

    - name: step2
      run: echo "test=world" >> "$GITHUB_OUTPUT"
      shell: powershell
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: homework
          path: math-homework.txt
    - name: step3
      run: sleep 20

  build2:
      runs-on: self-hosted
      needs:  build1
      steps:
      - name: step1
        run: |
          echo "Anil Test"
        shell: powershell
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: homework
      - shell: powershell
        run: |
          cat math-homework.txt
          echo  3+12  >> math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt
