name: Rust-OutPut

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  ANIL_ENV: anil

jobs:
  build2:
    runs-on: ubuntu-latest
    needs: build
    env:
      ANIL_ENV_job2: build2
    outputs:
      output1: ${{ env.ANIL_ENV_job2 }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - name: test-build2
      run: echo  ${{ env.ANIL_ENV }}
      shell: bash
    - name: evn
      run: echo "test=world" >> "$GITHUB_OUTPUT"
      shell: bash

  build3:
    env:
      ANIL_ENV2: ${{ needs.build2.outputs.output1 }}
    runs-on: ubuntu-latest
    needs: [build, build2]
    steps:
    - name: test-build3 
      run: |
        echo  ${{ env.ANIL_ENV }}
        echo  ${{ needs.build2.outputs.output2 }}
      shell: bash